using System;
using System.Globalization;
using System.IO;
using Flubu;
using Flubu.Builds;

namespace BuildScripts
{
    public class DatabaseBuildHelper
    {
        public DatabaseBuildHelper(ITaskContext context)
        {
            this.context = context;
        }

        public string TargetRdbms
        {
            get { return targetRdbms; }
            set { targetRdbms = value; }
        }

        public void GenerateDBConnectionDataFiles()
        {
            string fileName = "DatabaseProviderData.txt";

            context.WriteInfo("Resetting {0} file to '{1}'", fileName, TargetRdbms);
            string contentsFormat = @"// This file tells eEnvoyer build which RDBMS to use (possible values are 'oracle', 'sqlserver' and 'db2')
{0}";
            string contents = string.Format(
                CultureInfo.InvariantCulture,
                contentsFormat,
                TargetRdbms);
            File.WriteAllText(fileName, contents);

            fileName = "DBConnectionData_Oracle.txt";
            if (false == File.Exists(fileName))
            {
                if (HudsonHelper.IsRunningUnderHudson)
                {
                    contents = @"This file should contain your database connection data. Stick to the following format or the thing will fail!
server : gemaj
username : hudson";
                    context.WriteInfo("Autogenerated {0} file for Hudson", fileName);
                }
                else
                {
                    contents = @"This file should contain your Oracle database connection data. Stick to the following format or the thing will fail!
server : gemaj
username : testuser";
                    context.WriteInfo("Autogenerated {0} file for testuser", fileName);
                }

                File.WriteAllText(fileName, contents);
            }
            else
                context.WriteInfo("{0} file already exists, leaving it as it is", fileName);

            fileName = "DBConnectionData_SqlServer.txt";
            if (false == File.Exists(fileName))
            {
                contents = @"This file should contain your MS SQLServer database connection data. Stick to the following format or the thing will fail!
server : (local)
database : eEnvoyer
username : eenvoyer_admin
password : JungleJungle01!";
                context.WriteInfo("Autogenerated {0} file", fileName);

                File.WriteAllText(fileName, contents);
            }
            else
                context.WriteInfo("{0} file already exists, leaving it as it is", fileName);

            fileName = "DBConnectionData_DB2.txt";
            if (false == File.Exists(fileName))
            {
                contents = @"This file should contain your DB2 database connection data. Stick to the following format or the thing will fail!
server : gemaj:50000
database : SAMPLE
username : db2admin
password : JungleJungle01!";
                context.WriteInfo("Autogenerated {0} file", fileName);

                File.WriteAllText(fileName, contents);
            }
            else
                context.WriteInfo("{0} file already exists, leaving it as it is", fileName);
        }

        private readonly ITaskContext context;
        private string targetRdbms = "oracle";
    }
}